export enum UserProfileEventType {
  BIO_CHANGED = "BIO_CHANGED",
  PICTURE_CHANGED = "PICTURE_CHANGED",
  BANNER_CHANGED = "BANNER_CHANGED",
  NAME_CHANGED = "NAME_CHANGED",
  SURNAME_CHANGED = "SURNAME_CHANGED",
  BIRTHDAY_CHANGED = "BIRTHDAY_CHANGED",
  COLOR_CHANGED = "COLOR_CHANGED",
  HANDLE_CHANGED = "HANDLE_CHANGED",
}

export enum UserEventType {
  CHAT_PINNED = "CHAT_PINNED",
  CHAT_UNPINNED = "CHAT_UNPINNED",
}

export enum ChatEventType {
  MESSAGE_EDITED = "MESSAGE_EDITED",
  REACTION_ADDED = "REACTION_ADDED",
  REACTION_REMOVED = "REACTION_REMOVED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_PINNED = "MESSAGE_PINNED",
  MESSAGE_UNPINNED = "MESSAGE_UNPINNED",
  MEMBER_JOINED = "MEMBER_JOINED",
  MEMBER_LEFT = "MEMBER_LEFT",
  MESSAGE_READ = "MESSAGE_READ",
  SUB_CREATED = "SUB_CREATED",
  SUB_RENAMED = "SUB_RENAMED",
  SUB_DELETED = "SUB_DELETED",
  CHAT_RENAMED = "CHAT_RENAMED",
  CHAT_PICTURE_CHANGED = "CHAT_PICTURE_CHANGED",
}
